export interface CatcherGame {
  slug:         string
  title:        string
  intro:        string
  ctaLabel:     string
  hudLabel:     string   // what the score counter tracks
  catchLabel:   string   // button label
  dodgeLabel:   string   // button label
  catchReacts:  string[]
  dodgeReacts:  string[]
  missReacts:   string[]
  items: {
    catch: string[]
    dodge: string[]
  }
  endScreens: {
    perfect: string  // 100%
    great:   string  // 80%+
    ok:      string  // 60%+
    bad:     string  // <60%
  }
  facts: string[]
}

export const CATCHER_GAMES: Record<string, CatcherGame> = {
  'signal-drop': {
    slug:     'signal-drop',
    title:    'Signal Drop',
    intro:    'Training data incoming. AI learns from labeled examples — data where someone already marked the right answer. Raw data alone teaches nothing. Catch every labeled example. Dodge everything else.',
    ctaLabel: 'Start training',
    hudLabel: 'Clean data',
    catchLabel: 'CATCH IT',
    dodgeLabel: 'DODGE IT',
    catchReacts: [
      'Clean signal. Label confirmed.',
      'Good data. Into the set.',
      'Training improving.',
    ],
    dodgeReacts: [
      "That's noise. No label, no learning.",
      "Unlabeled. Can't train on this.",
      'Raw data. Dodge it.',
    ],
    missReacts: [
      'Lost a clean example. That one had a label.',
      'Training data gone.',
      'Missed a good signal.',
    ],
    items: {
      catch: [
        '1,000 chest X-rays each reviewed and annotated by three radiologists',
        'Emails flagged as spam by the actual users who reported them',
        'Photos tagged by trained wildlife biologists, species and age confirmed',
        'Loan applications with final court-verified fraud outcomes attached',
        'Audio clips timestamped by professional transcribers, dialect noted',
        'News articles fact-checked by three independent journalists before labeling',
        'Medical scans with biopsy-confirmed diagnoses as ground truth',
        'Customer reviews scored by trained moderators using a 47-point rubric',
        'Traffic footage with pedestrian positions confirmed by human reviewers',
        'Social media posts labeled for toxicity by native speakers of each language',
      ],
      dodge: [
        'A million web-scraped photos with no information about what\'s in them',
        'Translations auto-generated by another AI, never reviewed by a human',
        'Facial recognition training data scraped from public surveillance cameras',
        'Medical data from one hospital in one country, applied globally',
        'Sentiment labels applied by workers paid $0.01 per image, 30 seconds each',
        'Historical hiring decisions from a company with documented discrimination lawsuits',
        'User behavior data collected without disclosing it would train a model',
        'Reviews filtered to only include 1-star and 5-star ratings, nothing in between',
        'Crime data from a neighborhood that was over-policed for 20 years',
        'Survey responses where half the participants misunderstood the question',
      ],
    },
    endScreens: {
      perfect: 'Spotless training set. PAI learned everything it could.',
      great:   'Strong dataset. A few gaps but the model will train well.',
      ok:      'Noisy data. The model will learn some bad patterns along with the good ones.',
      bad:     'Too much noise. The model learned the wrong things. This is how bias starts.',
    },
    facts: [
      'Supervised learning uses labeled examples. Someone had to mark every single one.',
      "AI doesn't label its own training data — humans do.",
      'The labels in a training set carry the biases of whoever made them.',
      'If a human labeled something wrong, the model learns that wrong label as truth.',
      "More data doesn't fix bad data. A model is only as good as its training set.",
      "Unsupervised learning works without labels — but the model finds patterns humans never named. Someone still has to interpret what those patterns mean.",
      "Amazon's hiring tool was trained on years of real hiring decisions. The labels were real. The bias in those labels was also real. The model learned both.",
    ],
  },
}
